#!/bin/sh
#Assignment Part B Scripting requirement 1"
#author Rebecca Paton
#Student ID S3338805
##
#This script is to take a single input and based on the input do one of 
#4 things.(So I choose case $1 to do this) 
#Option1 Get Free memory in human readable format
FREE=/usr/bin/free
#Option2 Get free and used disk space in human readable format
DF=/bin/df
#Option3 Get Connection information for all network ports
IP=/bin/ip
#Option4 Get System uptime
UPTIME=/usr/bin/uptime
#
#man page included PartB1.1

case $1 in 
	"1")
		echo "Mem and Swap values are"
		$FREE -h | awk '{print $2 " " $3}'
;;
	"2")
		echo "Disk Free and Used space is"
		$DF -h -l | awk '{print $1 " " $2 " " $3 " " $4}'
;;
	"3")
		echo "Network Inforamation is"
		$IP addr sho | awk '{print $1 " " $2}'
;;
	"4")
		$UPTIME | awk '{print}'
;;
	*)
		echo "Sorry, I did not understand your request. Please provide an integer between 1 and 4"
esac
