#!/bin/sh
#Assignment Part B Scripting requirement 1"
#author Rebecca Paton
#Student ID S3338805
##
#This script is to take a single inport and based on the input do one of 
#4 things.(So I choose case $1 to do this) 
#
#Option1 Get Free memory in human readable format
FREE=/usr/bin/free
#Option2 Get free and used disk space in human readable format
#Option3 Get Connection information for all network ports
#Option4 Get System uptime
#
#

case $1 in 
	"1")
		echo "Mem and Swap values are"
		$FREE -h | awk '{print $2 " " $3}'
;;
	"2")
		echo "choice 2"
;;
	"3")
		echo "choice 3"
;;
	"4")
		echo "choice 4"
;;
	*)
		echo "Sorry, I did not understand your request. Please choose and integer between 1 and 4"
esac
